name: Test Cacao

on: push

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
         - name: "Windows Latest MSVC"
           artifacts: "./Examples/build/HelloWorld/Cacao/RelWithDebInfo/*.dll\n./Examples/build/**/RelWithDebInfo/*.dll"
           os: windows-latest
           extra_flags: "-T host=x86 -A win32"
           build_type: "RelWithDebInfo"
           cc: "cl"
           cxx: "cl"
         - name: "macOS Latest Clang"
           artifacts: "./Examples/build/HelloWorld/Cacao/*.dylib\n./Examples/build/**/*.dylib"
           os: macos-latest
           extra_flags: ""
           build_type: "RelWithDebInfo"
           cc: "clang"
           cxx: "clang++"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
      if: matrix.config.os == 'windows-latest'

    - name: Configure CMake
      working-directory: ./Examples
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} ${{ matrix.config.extra_flags }}

    - name: Build
      working-directory: ./Examples
      # Build your program with the given configuration
      run: cmake --build build --config ${{ matrix.config.build_type }} --target Cacao

    - name: Upload ${{ matrix.config.name }} Binaries
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.config.name }} Binaries
        path: ${{ matrix.config.artifacts }}
